# -*- coding: utf-8 -*-
"""Project-97.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SSkF36y64RdkS7Kil8ti4lQqH7Ocu2hr
"""

import random
rano = random.randrange(1,9)
chances  = 0

while chances < 5:
  guess = int(input("guess the number"))
  if(guess == rano):
    print("You Won")
    break
  else:
    chances = chances + 1
    if(guess < rano):
      print("Wrong Guess: Guess a number higher than " + str(guess))
    else:
      print("Wrong Guess: Guess a number lower than " + str(guess))
      
if(chances >= 5):
  print("You Lost")